import { runPlatformWebConsoleTests } from "./component/platform-web-console.test";
import { runAdvancedInfrastructureTests } from "./unit/advanced-infrastructure.test";
import { runCommunityContractTests } from "./unit/community-contract.test";
import { runCommunityApiProjectionTests } from "./unit/community-api-projection.test";
import { runCommunityObjectProjectionTests } from "./unit/community-object-projection.test";
import { runCommunityProjectionExecutionTests } from "./unit/community-projection-execution.test";
import { runCommunitySearchReferenceBackendTests } from "./unit/community-search-reference-backend.test";
import { runCommunitySearchEntityFieldTests } from "./unit/community-search-entity-fields.test";
import { runCommunitySourceAdapterTests } from "./unit/community-source-adapters.test";
import { runCommunityStateStoreTests } from "./unit/community-state-store.test";
import { runCommunityCoverageTests } from "./unit/community-coverage.test";
import { runCommunityOperationsWebTests } from "./unit/community-operations-web.test";
import { runCommunityOramaBackendTests } from "./unit/community-orama-backend.test";
import { runCommunitySqliteSearchTests } from "./unit/community-sqlite-search.test";
import { runCommunitySearchCliTests } from "./unit/community-search-cli.test";
import { runCommunityWebRenderParityTests } from "./unit/community-web-render-parity.test";
import { runNightboardThemeTests } from "./unit/nightboard-themes.test";
import { runNightboardNavigationRuntimeTests } from "./unit/nightboard-navigation-runtime.test";
import { runCommunityWebTextBudgetTests } from "./unit/community-web-text-budget.test";
import { runCommunityWebVercelTests } from "./unit/community-web-vercel.test";
import { runEpochIntegrationSuiteTests } from "./unit/epoch-integration-suite.test";
import { runEpochLiveReduxTests } from "./unit/epoch-live-redux.test";
import { runEpochLiveStoreTests } from "./unit/epoch-live-store.test";
import { runEpochLiveYjsTests } from "./unit/epoch-live-yjs.test";
import { runPlatformBoundaryTests } from "./unit/platform-boundaries.test";
import { runPlatformCommunityModuleTests } from "./unit/platform-community-module.test";
import { runPlatformProductionCoreTests } from "./unit/platform-production-core.test";
import { runPersonaFeatureModelTests } from "./unit/persona-feature-model.test";
import { runPersonaMapTests } from "./unit/persona-map.test";
import { runEpochLiveReactTests } from "./component/epoch-live-react.test";
import { runSampleEpochLiveCollabTests } from "./unit/sample-epoch-live-collab.test";
import { runSampleHelloWorldCliTests } from "./unit/sample-hello-world-cli.test";
import { runSampleSelfEvolvingCanvasTests } from "./unit/sample-self-evolving-canvas.test";
import { runSampleSelfEvolvingDashboardTests } from "./unit/sample-self-evolving-dashboard.test";
import { runVirtualCheckoutTests } from "./unit/virtual-checkout.test";
import { runCompositionSelectionTests } from "./unit/composition-selection.test";
import { runWasmReactShadowDomTests } from "./component/wasm-react-shadow-dom.test";
import { runWasmReactStoreTests } from "./unit/wasm-react-store.test";
import { runGitProjectionTests } from "./unit/git-projection.test";
import { runGitProxyTests } from "./unit/git-proxy.test";
import { runAtprotoCommunityTests } from "./unit/atproto-community.test";
import { runGossipAtprotoIntegrationTests } from "./unit/gossip-atproto-integration.test";
import { runIdentityBridgeTests } from "./unit/identity-bridge.test";
import { runChangeGraphStoreTests } from "./unit/change-graph-store.test";
import { runConvergenceChangeGraphTests } from "./unit/convergence-change-graph.test";
import { runConvergenceCoreTransactionTests } from "./unit/convergence-core-transactions.test";
import { runCoreStorageSyncV2Tests } from "./unit/core-storage-sync-v2.test";
import { runGitConvergenceFoundationTests } from "./unit/git-convergence-foundation.test";
import { runProtocolRequiredEventTests } from "./unit/protocol-required-events.test";
import { runSpaceCliTests, runSpaceTests } from "./unit/spaces.test";
import { runSpaceRuntimeTests } from "./unit/spaces-runtime.test";
import { runChangeGraphBrowserWrapperTests } from "./unit/change-graph-browser-wrappers.test";
import { runChangeGraphCliTests } from "./unit/change-graph-cli.test";
import { runNomenclatureContractTests } from "./unit/nomenclature-contract.test";
import { runSemanticPipelineTests } from "./unit/semantic-pipeline.test";
import { runExtensionMechanismTests } from "./unit/extension-mechanism.test";
import { runExtensionCliTests } from "./unit/extension-cli.test";
import { runCodeOperationContextTests } from "./unit/code-operation-context.test";

async function main(): Promise<void> {
  runAdvancedInfrastructureTests();
  runPlatformProductionCoreTests();
  await runPlatformCommunityModuleTests();
  runPlatformWebConsoleTests();
  await runCommunityContractTests();
  await runCommunityObjectProjectionTests();
  await runCommunityProjectionExecutionTests();
  await runCommunitySearchReferenceBackendTests();
  await runCommunitySearchEntityFieldTests();
  await runCommunitySourceAdapterTests();
  await runCommunityStateStoreTests();
  await runCommunityOramaBackendTests();
  await runCommunitySqliteSearchTests();
  await runCommunitySearchCliTests();
  await runCommunityApiProjectionTests();
  await runCommunityCoverageTests();
  await runCommunityOperationsWebTests();
  await runCommunityWebVercelTests();
  await runCommunityWebRenderParityTests();
  await runNightboardThemeTests();
  await runNightboardNavigationRuntimeTests();
  await runCommunityWebTextBudgetTests();
  await runEpochIntegrationSuiteTests();
  await runPlatformBoundaryTests();
  runPersonaFeatureModelTests();
  runPersonaMapTests();
  runWasmReactStoreTests();
  runEpochLiveStoreTests();
  runEpochLiveReduxTests();
  runEpochLiveYjsTests();
  runSampleEpochLiveCollabTests();
  runSampleHelloWorldCliTests();
  runSampleSelfEvolvingCanvasTests();
  runSampleSelfEvolvingDashboardTests();
  runVirtualCheckoutTests();
  await runCompositionSelectionTests();
  runGitProjectionTests();
  await runGitProxyTests();
  await runAtprotoCommunityTests();
  await runGossipAtprotoIntegrationTests();
  await runIdentityBridgeTests();
  runChangeGraphStoreTests();
  runConvergenceChangeGraphTests();
  await runConvergenceCoreTransactionTests();
  await runCoreStorageSyncV2Tests();
  await runGitConvergenceFoundationTests();
  runProtocolRequiredEventTests();
  runChangeGraphBrowserWrapperTests();
  await runChangeGraphCliTests();
  await runSpaceTests();
  await runSpaceCliTests();
  await runSpaceRuntimeTests();
  await runNomenclatureContractTests();
  runSemanticPipelineTests();
  runExtensionMechanismTests();
  runExtensionCliTests();
  runCodeOperationContextTests();
  await runWasmReactShadowDomTests();
  await runEpochLiveReactTests();
  console.log("unit and component tests passed");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
