import { runPlatformWebConsoleTests } from "./component/platform-web-console.test";
import { runAdvancedInfrastructureTests } from "./unit/advanced-infrastructure.test";
import { runCommunityContractTests } from "./unit/community-contract.test";
import { runCommunityApiProjectionTests } from "./unit/community-api-projection.test";
import { runCommunityObjectProjectionTests } from "./unit/community-object-projection.test";
import { runCommunityProjectionExecutionTests } from "./unit/community-projection-execution.test";
import { runCommunitySearchReferenceBackendTests } from "./unit/community-search-reference-backend.test";
import { runCommunitySearchEntityFieldTests } from "./unit/community-search-entity-fields.test";
import { runCommunitySourceAdapterTests } from "./unit/community-source-adapters.test";
import { runCommunityStateStoreTests } from "./unit/community-state-store.test";
import { runCommunityCoverageTests } from "./unit/community-coverage.test";
import { runCommunityRuntimeTests } from "./unit/community-runtime.test";
import { runCommunityStreamPolicyTests } from "./unit/community-stream-policy.test";
import { runCommunityBoardHonestyTests } from "./unit/community-board-honesty.test";
import { runCommunityOperationsWebTests } from "./unit/community-operations-web.test";
import { runCommunityOramaBackendTests } from "./unit/community-orama-backend.test";
import { runCommunitySqliteSearchTests } from "./unit/community-sqlite-search.test";
import { runCommunitySearchCliTests } from "./unit/community-search-cli.test";
import { runCommunityWebRenderParityTests } from "./unit/community-web-render-parity.test";
import { runCommunityWebAppThemeTests } from "./unit/community-web-app-themes.test";
import { runCommunityWebAppWebMcpTests } from "./unit/community-web-app-webmcp.test";
import { runCommunityWebAppNavigationRuntimeTests } from "./unit/community-web-app-navigation-runtime.test";
import { runCommunityWebTextBudgetTests } from "./unit/community-web-text-budget.test";
import { runCommunityWebVercelTests } from "./unit/community-web-vercel.test";
import { runEpochIntegrationSuiteTests } from "./unit/epoch-integration-suite.test";
import { runEpochLiveReduxTests } from "./unit/epoch-live-redux.test";
import { runEpochLiveStoreTests } from "./unit/epoch-live-store.test";
import { runEpochLiveYjsTests } from "./unit/epoch-live-yjs.test";
import { runPlatformBoundaryTests } from "./unit/platform-boundaries.test";
import { runPlatformCommunityModuleTests } from "./unit/platform-community-module.test";
import { runNatsStreamCoverageTests } from "./unit/nats-stream-coverage.test";
import { runNatsServiceDiscoveryTests } from "./unit/nats-service-discovery.test";
import { runNatsMutationOracleTests } from "./unit/nats-mutation-oracles.test";
import { runVerifyCharacterizationTests } from "./unit/verify-characterization.test";
import { runVerifyHelperTests } from "./unit/verify-helper.test";
import { runOpenZlCodecTests } from "./unit/openzl-codec.test";
import { runPlatformFabricCredentialTests } from "./unit/platform-fabric-credentials.test";
import { runPlatformFabricNatsContractTests } from "./unit/platform-fabric-nats-contract.test";
import { runFabricAuthAdversarialMutationTests } from "./unit/fabric-auth-adversarial-mutation.test";
import { runPostureTests } from "./unit/posture.test";
import { runChannelEventTests } from "./unit/channel-events.test";
import { runExitBundleTests } from "./unit/exit-bundle.test";
import { runFabricJwtTests } from "./unit/fabric-jwt.test";
import { runRealPdsTests } from "./unit/real-pds.test";
import { runXmppTransportTests } from "./unit/xmpp-transport.test";
import { runProtocolExperimentTests } from "./unit/protocol-experiments/registry.test";
import { runAdversarialPostureTests } from "./unit/adversarial/posture/invariants.test";
import { runAdversarialChannelTests } from "./unit/adversarial/channels/invariants.test";
import { runPlatformProductionCoreTests } from "./unit/platform-production-core.test";
import { runPersonaFeatureModelTests } from "./unit/persona-feature-model.test";
import { runPersonaMapTests } from "./unit/persona-map.test";
import { runEpochLiveReactTests } from "./component/epoch-live-react.test";
import { runSampleEpochLiveCollabTests } from "./unit/sample-epoch-live-collab.test";
import { runSampleHelloWorldCliTests } from "./unit/sample-hello-world-cli.test";
import { runSampleSelfEvolvingCanvasTests } from "./unit/sample-self-evolving-canvas.test";
import { runSampleSelfEvolvingDashboardTests } from "./unit/sample-self-evolving-dashboard.test";
import { runVirtualCheckoutTests } from "./unit/virtual-checkout.test";
import { runCompositionSelectionTests } from "./unit/composition-selection.test";
import { runWasmReactShadowDomTests } from "./component/wasm-react-shadow-dom.test";
import { runWasmReactStoreTests } from "./unit/wasm-react-store.test";
import { runGitProjectionTests } from "./unit/git-projection.test";
import { runGitProxyTests } from "./unit/git-proxy.test";
import { runAtprotoCommunityTests } from "./unit/atproto-community.test";
import { runGossipAtprotoIntegrationTests } from "./unit/gossip-atproto-integration.test";
import { runIdentityBridgeTests } from "./unit/identity-bridge.test";
import { runChangeGraphStoreTests } from "./unit/change-graph-store.test";
import { runConvergenceChangeGraphTests } from "./unit/convergence-change-graph.test";
import { runConvergenceCoreTransactionTests } from "./unit/convergence-core-transactions.test";
import { runCoreStorageSyncV2Tests } from "./unit/core-storage-sync-v2.test";
import { runGitConvergenceFoundationTests } from "./unit/git-convergence-foundation.test";
import { runProtocolRequiredEventTests } from "./unit/protocol-required-events.test";
import { runProtocolEventBodyTests } from "./unit/protocol-event-bodies.test";
import { runCliGitTests } from "./unit/cli-git.test";
import { runCommunityWebStatesPwaTests } from "./unit/community-web-states-pwa.test";
import { runSpaceCliTests, runSpaceTests } from "./unit/spaces.test";
import { runSpaceRuntimeTests } from "./unit/spaces-runtime.test";
import { runLiveSpacesPolicyTests } from "./unit/live-spaces-policy.test";
import { runLiveSpacesLogTests } from "./unit/live-spaces-log.test";
import { runLiveSpacesCoreTests } from "./unit/live-spaces-core.test";
import { runLiveSpacesCommandTests } from "./unit/live-spaces-commands.test";
import { runChangeGraphBrowserWrapperTests } from "./unit/change-graph-browser-wrappers.test";
import { runChangeGraphCliTests } from "./unit/change-graph-cli.test";
import { runNomenclatureContractTests } from "./unit/nomenclature-contract.test";
import { runSemanticPipelineTests } from "./unit/semantic-pipeline.test";
import { runExtensionMechanismTests } from "./unit/extension-mechanism.test";
import { runExtensionCliTests } from "./unit/extension-cli.test";
import { runWasmProviderTests } from "./unit/wasm-providers.test";
import { runTomlParserTests } from "./unit/toml-parser.test";
import { runVerifiedLaunchTests } from "./unit/verified-launch.test";
import { runPublisherLifecycleTests } from "./unit/publisher-lifecycle.test";
import { runMixedCompressionTests } from "./unit/mixed-compression.test";
import { runProviderLoadingTests } from "./unit/provider-loading.test";
import { runCliCoverageTests } from "./unit/cli-coverage.test";
import { runHaSeedTests } from "./unit/ha-seed.test";
import { runCodeOperationContextTests } from "./unit/code-operation-context.test";

async function main(): Promise<void> {
  runAdvancedInfrastructureTests();
  await runHaSeedTests();
  await runCliCoverageTests();
  runOpenZlCodecTests();
  runNatsStreamCoverageTests();
  await runNatsServiceDiscoveryTests();
  runNatsMutationOracleTests();
  await runVerifyCharacterizationTests();
  runVerifyHelperTests();
  runPlatformProductionCoreTests();
  runPlatformFabricCredentialTests();
  await runPlatformFabricNatsContractTests();
  await runFabricAuthAdversarialMutationTests();
  runPostureTests();
  await runChannelEventTests();
  runExitBundleTests();
  runFabricJwtTests();
  await runRealPdsTests();
  await runXmppTransportTests();
  runProtocolExperimentTests();
  await runAdversarialPostureTests();
  runAdversarialChannelTests();
  await runPlatformCommunityModuleTests();
  runPlatformWebConsoleTests();
  await runCommunityContractTests();
  await runCommunityObjectProjectionTests();
  await runCommunityProjectionExecutionTests();
  await runCommunitySearchReferenceBackendTests();
  await runCommunitySearchEntityFieldTests();
  await runCommunitySourceAdapterTests();
  await runCommunityStateStoreTests();
  await runCommunityOramaBackendTests();
  await runCommunitySqliteSearchTests();
  await runCommunitySearchCliTests();
  await runCommunityApiProjectionTests();
  await runCommunityCoverageTests();
  await runCommunityRuntimeTests();
  runCommunityStreamPolicyTests();
  await runCommunityBoardHonestyTests();
  await runCommunityOperationsWebTests();
  await runCommunityWebVercelTests();
  await runCommunityWebRenderParityTests();
  await runCommunityWebAppThemeTests();
  await runCommunityWebAppWebMcpTests();
  await runCommunityWebAppNavigationRuntimeTests();
  await runCommunityWebTextBudgetTests();
  await runEpochIntegrationSuiteTests();
  await runPlatformBoundaryTests();
  runPersonaFeatureModelTests();
  runPersonaMapTests();
  runWasmReactStoreTests();
  runEpochLiveStoreTests();
  runEpochLiveReduxTests();
  runEpochLiveYjsTests();
  runSampleEpochLiveCollabTests();
  runSampleHelloWorldCliTests();
  runSampleSelfEvolvingCanvasTests();
  runSampleSelfEvolvingDashboardTests();
  runVirtualCheckoutTests();
  await runCompositionSelectionTests();
  runGitProjectionTests();
  await runGitProxyTests();
  await runAtprotoCommunityTests();
  await runGossipAtprotoIntegrationTests();
  await runIdentityBridgeTests();
  runChangeGraphStoreTests();
  runConvergenceChangeGraphTests();
  await runConvergenceCoreTransactionTests();
  await runCoreStorageSyncV2Tests();
  await runGitConvergenceFoundationTests();
  runProtocolRequiredEventTests();
  runProtocolEventBodyTests();
  runCliGitTests();
  await runCommunityWebStatesPwaTests();
  runChangeGraphBrowserWrapperTests();
  await runChangeGraphCliTests();
  await runSpaceTests();
  await runSpaceCliTests();
  await runSpaceRuntimeTests();
  runLiveSpacesPolicyTests();
  runLiveSpacesLogTests();
  await runLiveSpacesCoreTests();
  await runLiveSpacesCommandTests();
  await runNomenclatureContractTests();
  runSemanticPipelineTests();
  runExtensionMechanismTests();
  runExtensionCliTests();
  runWasmProviderTests();
  runTomlParserTests();
  runVerifiedLaunchTests();
  runPublisherLifecycleTests();
  runMixedCompressionTests();
  runProviderLoadingTests();
  runCodeOperationContextTests();
  await runWasmReactShadowDomTests();
  await runEpochLiveReactTests();
  console.log("unit and component tests passed");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
