/**
 * Step implementations for `community-web-responsive-craft`.
 * Auto-generated by optimizexp harness. Prefer real commands when discovery is confident.
 * Agent may refine; do not call live third-party services from default tests.
 */
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import type { OptimizexpWorld } from "./world.ts";

/** Discovery snapshot — see discovery.json for full report. */
export const DISCOVERY_PRIMARY = {
  command: "pnpm run vercel:community-web" as string | null,
  confidence: "high",
  reason: "package.json scripts[\"vercel:community-web\"] exists; mentioned in feature/seed",
};

export const IMPLEMENTATION_STATUS = {
  exerciseSurface: DISCOVERY_PRIMARY.command ? "wired" : "stub",
  criticalPath: "stub",
  failurePath: DISCOVERY_PRIMARY.command ? "wired" : "stub",
} as const;

export function setPersona(world: OptimizexpWorld, personaId: string): void {
  world.personaId = personaId;
  world.notes.push(`persona active: ${personaId}`);
}

export function setFeatureContext(world: OptimizexpWorld, featureId: string): void {
  world.featureId = featureId;
  world.notes.push(`feature under review: ${featureId}`);
}

export function onCriticalPath(world: OptimizexpWorld): void {
  // Prefer asserting local artifacts / seed presence over network.
  const seed = path.join(
    process.cwd(),
    ".optimizexp/features",
    world.featureId,
    "SEED.md",
  );
  const featureJson = path.join(
    process.cwd(),
    ".optimizexp/features",
    world.featureId,
    "feature.json",
  );
  if (!existsSync(seed) && !existsSync(featureJson)) {
    world.notes.push("critical path: feature folder incomplete");
    return;
  }
  world.notes.push("critical path: feature seed/metadata present");
  world.statusClear = true;
}

/**
 * Exercise the discovered surface command when confidence is high/medium.
 * Captures stdout/stderr/exit for Then-steps and evidence hooks.
 */
export function exerciseSurface(world: OptimizexpWorld): void {
  const command = DISCOVERY_PRIMARY.command;
  if (!command) {
    world.notes.push("exerciseSurface: STUB — no discovered command");
    world.lastExitCode = null;
    world.statusClear = false;
    world.nextActionObvious = false;
    return;
  }
  world.lastCommand = command;
  const r = spawnSync("bash", ["-lc", command], {
    cwd: process.cwd(),
    encoding: "utf8",
    timeout: 120_000,
    maxBuffer: 4 * 1024 * 1024,
    env: { ...process.env },
  });
  world.lastExitCode = r.status;
  world.lastStdout = r.stdout ?? "";
  world.lastStderr = r.stderr ?? "";
  world.notes.push(
    `exerciseSurface: ran ${command} → exit ${r.status} (${DISCOVERY_PRIMARY.confidence}: ${DISCOVERY_PRIMARY.reason})`,
  );
  // Heuristic status clarity: non-empty output or known gate names
  const out = `${world.lastStdout}\n${world.lastStderr}`;
  world.statusClear = out.trim().length > 0 || r.status === 0;
  world.nextActionObvious =
    /error|fail|fix|run |see |hint|path:/i.test(out) || r.status === 0;
  world.errorActionable =
    r.status !== 0 && /error|fail|ENOENT|must|required|path/i.test(out);
}

export function observeFailure(world: OptimizexpWorld): void {
  // Re-use exercise; failure scenarios may intentionally accept non-zero.
  exerciseSurface(world);
  if (world.lastExitCode === 0) {
    world.notes.push(
      "observeFailure: command succeeded; treat as soft fail for UX path or refine step",
    );
  }
  world.errorActionable =
    world.errorActionable ||
    (world.lastExitCode !== 0 &&
      `${world.lastStdout}\n${world.lastStderr}`.trim().length > 0);
}

export function assertClearStatus(world: OptimizexpWorld): void {
  if (!world.statusClear) {
    throw new Error(
      `Expected clear status from surface; notes=${world.notes.join(" | ")} stdout=${world.lastStdout.slice(0, 200)}`,
    );
  }
}

export function assertNextActionObvious(world: OptimizexpWorld): void {
  if (!world.nextActionObvious && world.lastExitCode !== 0) {
    throw new Error(
      `Expected obvious next action on failure; stderr=${world.lastStderr.slice(0, 300)}`,
    );
  }
}

export function assertErrorActionable(world: OptimizexpWorld): void {
  if (world.lastExitCode === 0) return; // success path ok
  if (!world.errorActionable) {
    throw new Error(
      `Expected actionable error output; exit=${world.lastExitCode}`,
    );
  }
}

export function markEvidenceCapturable(world: OptimizexpWorld): void {
  world.evidencePath = `.optimizexp/features/${world.featureId}/evidence/`;
  world.notes.push(`evidence capturable under ${world.evidencePath}`);
}
