import { z } from "zod";

export const CliCommand = {
  create: "create",
  init: "init",
  push: "push",
  record: "record",
  track: "track",
  forget: "forget",
  mv: "mv",
  rm: "rm",
  cp: "cp",
  intent: "intent",
  events: "events",
  verify: "verify",
  merge: "merge",
  reject: "reject",
  comment: "comment",
  issue: "issue",
  review: "review",
  ciRecord: "ci-record",
  gateStatus: "gate-status",
  opLog: "op-log",
  opShow: "op-show",
  redact: "redact",
  redactPlan: "redact-plan",
  status: "status",
  checkIgnore: "check-ignore",
  config: "config",
  main: "main",
  resolve: "resolve",
  sync: "sync",
  gossip: "gossip",
  publishArtifacts: "publish-artifacts",
  rollback: "rollback",
  viewCreate: "view-create",
  views: "views",
  checkout: "checkout",
  viewDelete: "view-delete",
  viewDiff: "view-diff",
  viewPromote: "view-promote",
  version: "version",
  versions: "versions",
  import: "import",
  export: "export",
  drPlan: "dr-plan",
  preview: "preview",
  hydrate: "hydrate",
} as const;

export const CliOption = {
  author: "author",
  type: "type",
  title: "title",
  description: "description",
  reason: "reason",
  label: "label",
  path: "path",
  recordResolution: "record-resolution",
  state: "state",
  body: "body",
  name: "name",
  status: "status",
  review: "review",
  ci: "ci",
  intent: "intent",
  rule: "rule",
  parent: "parent",
  version: "version",
  message: "message",
  entity: "entity",
  view: "view",
  out: "out",
  force: "force",
  includeIgnored: "include-ignored",
  ignored: "ignored",
  scope: "scope",
  json: "json",
  noVersion: "no-version",
  virtual: "virtual",
  full: "full",
  base: "base",
  context: "context",
  peer: "peer",
  did: "did",
  visibility: "visibility",
  mode: "mode",
  serve: "serve",
  port: "port",
  repo: "--repo",
} as const;

export const CliSyntax = {
  repositoryDefault: ".",
  optionPrefix: "--",
} as const;

export const CliText = {
  ok: "ok",
  verificationFailed: "verification failed",
  usage: "usage: epoch [--repo PATH] <help|create|init|push|record|track|forget|mv|rm|cp|intent|events|verify|merge|reject|comment|issue|review|ci-record|gate-status|op-log|op-show|redact|redact-plan|status|check-ignore|config|main|resolve|sync|gossip|publish-artifacts|rollback|view-create|views|checkout|view-delete|view-diff|view-promote|version|versions|import|export|dr-plan|preview|hydrate|new|change|log|op|graph|split|bundle|merge-plan|conflict|workspace|clone|fetch|backfill|mirror|principal|agent|forge|swhid|archive|interop>",
  createUsage: "usage: epoch create [--author NAME] [PATH]",
  pushUsage: "usage: epoch push [--author NAME] [--version NAME] [--message TEXT] [--no-version] [PATH...]",
  trackUsage: "usage: epoch track [--author NAME] [--type MIME] [--include-ignored] PATH",
  forgetUsage: "usage: epoch forget [--author NAME] PATH",
  mvUsage: "usage: epoch mv [--author NAME] FROM TO",
  rmUsage: "usage: epoch rm [--author NAME] PATH",
  cpUsage: "usage: epoch cp [--author NAME] FROM TO",
  checkIgnoreUsage: "usage: epoch check-ignore PATH",
  configUsage: "usage: epoch config <get|path> ...",
  configGetUsage: "usage: epoch config get KEY",
  configPathUsage: "usage: epoch config path [--scope local|shared]",
  intentUsage: "usage: epoch intent [--author NAME] [--type MIME] [--title TEXT] [--description TEXT] [--label A,B] PATH",
  mergeUsage: "usage: epoch merge [--author NAME] [--title TEXT] [--description TEXT] [--reason TEXT] [--label A,B] INTENT_ID",
  rejectUsage: "usage: epoch reject [--author NAME] [--title TEXT] [--description TEXT] [--reason TEXT] [--label A,B] INTENT_ID",
  commentUsage: "usage: epoch comment [--author NAME] [--intent INTENT_ID] [--title TEXT] [--description TEXT] [--label A,B] BODY",
  issueUsage: "usage: epoch issue [--author NAME] --title TEXT BODY",
  reviewUsage: "usage: epoch review [--author NAME] --state STATE --body TEXT INTENT_ID",
  ciRecordUsage: "usage: epoch ci-record [--author NAME] --name NAME --status STATUS INTENT_ID",
  gateStatusUsage: "usage: epoch gate-status [--review STATE] [--ci NAME] INTENT_ID",
  opShowUsage: "usage: epoch op-show EVENT_ID",
  redactUsage: "usage: epoch redact [--author NAME] [--reason TEXT] BLOB_SHA256",
  redactPlanUsage: "usage: epoch redact-plan BLOB_SHA256",
  resolveUsage: "usage: epoch resolve --type MIME [--path ENTITY_PATH] [--record-resolution RESOLVED] BASE LEFT RIGHT",
  rollbackUsage: "usage: epoch rollback EVENT_ID",
  viewCreateUsage: "usage: epoch view-create [--rule JSON] [--parent VIEW] NAME",
  checkoutUsage: "usage: epoch checkout [--virtual|--full] [--base REF] VIEW",
  viewDeleteUsage: "usage: epoch view-delete VIEW",
  viewDiffUsage: "usage: epoch view-diff FROM TO",
  viewPromoteUsage: "usage: epoch view-promote SOURCE TARGET",
  versionUsage: "usage: epoch version <create|show|materialize> ...",
  versionCreateUsage: "usage: epoch version create [--view VIEW] [--entity NAME] [--description TEXT] [NAME]",
  versionShowUsage: "usage: epoch version show VERSION",
  versionMaterializeUsage: "usage: epoch version materialize VERSION --out PATH [--base REF] [--force]",
  previewUsage: "usage: epoch preview [--view VIEW] [--base REF] [--context N]",
  hydrateUsage: "usage: epoch hydrate [PATH...]",
} as const;

export const ParsedArgsSchema = z.object({
  repo: z.string().min(1),
  command: z.string().optional(),
  args: z.array(z.string()),
});
