/**
 * Generate Cucumber bindings, world, implementations, and Vitest stubs for a feature.
 */
import type { DiscoveryReport, DiscoveredBinding } from "./code-discovery.mts";
import { pickPrimaryCommand } from "./code-discovery.mts";

export function generateWorldTs(featureId: string): string {
	return `/**
 * OptimizeXP World for feature \`${featureId}\`.
 * Shared mutable state for Cucumber steps — no live external services.
 */
export type OptimizexpWorld = {
  featureId: string;
  personaId: string | null;
  lastExitCode: number | null;
  lastStdout: string;
  lastStderr: string;
  lastCommand: string | null;
  notes: string[];
  statusClear: boolean;
  nextActionObvious: boolean;
  errorActionable: boolean;
  evidencePath: string | null;
};

export function createWorld(featureId: string): OptimizexpWorld {
  return {
    featureId,
    personaId: null,
    lastExitCode: null,
    lastStdout: "",
    lastStderr: "",
    lastCommand: null,
    notes: [],
    statusClear: false,
    nextActionObvious: false,
    errorActionable: false,
    evidencePath: null,
  };
}
`;
}

export function generateImplementationsTs(input: {
	featureId: string;
	primary: DiscoveredBinding | null;
	report: DiscoveryReport;
}): string {
	const cmd = input.primary?.command
		? JSON.stringify(input.primary.command)
		: "null";
	const conf = input.primary?.confidence ?? "none";
	const reason = input.primary?.reason
		? JSON.stringify(input.primary.reason)
		: JSON.stringify("no binding");

	return `/**
 * Step implementations for \`${input.featureId}\`.
 * Auto-generated by optimizexp harness. Prefer real commands when discovery is confident.
 * Agent may refine; do not call live third-party services from default tests.
 */
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import type { OptimizexpWorld } from "./world.ts";

/** Discovery snapshot — see discovery.json for full report. */
export const DISCOVERY_PRIMARY = {
  command: ${cmd} as string | null,
  confidence: ${JSON.stringify(conf)},
  reason: ${reason},
};

export const IMPLEMENTATION_STATUS = {
  exerciseSurface: DISCOVERY_PRIMARY.command ? "wired" : "stub",
  criticalPath: "stub",
  failurePath: DISCOVERY_PRIMARY.command ? "wired" : "stub",
} as const;

export function setPersona(world: OptimizexpWorld, personaId: string): void {
  world.personaId = personaId;
  world.notes.push(\`persona active: \${personaId}\`);
}

export function setFeatureContext(world: OptimizexpWorld, featureId: string): void {
  world.featureId = featureId;
  world.notes.push(\`feature under review: \${featureId}\`);
}

export function onCriticalPath(world: OptimizexpWorld): void {
  // Prefer asserting local artifacts / seed presence over network.
  const seed = path.join(
    process.cwd(),
    ".optimizexp/features",
    world.featureId,
    "SEED.md",
  );
  const featureJson = path.join(
    process.cwd(),
    ".optimizexp/features",
    world.featureId,
    "feature.json",
  );
  if (!existsSync(seed) && !existsSync(featureJson)) {
    world.notes.push("critical path: feature folder incomplete");
    return;
  }
  world.notes.push("critical path: feature seed/metadata present");
  world.statusClear = true;
}

/**
 * Exercise the discovered surface command when confidence is high/medium.
 * Captures stdout/stderr/exit for Then-steps and evidence hooks.
 */
export function exerciseSurface(world: OptimizexpWorld): void {
  const command = DISCOVERY_PRIMARY.command;
  if (!command) {
    world.notes.push("exerciseSurface: STUB — no discovered command");
    world.lastExitCode = null;
    world.statusClear = false;
    world.nextActionObvious = false;
    return;
  }
  world.lastCommand = command;
  const r = spawnSync("bash", ["-lc", command], {
    cwd: process.cwd(),
    encoding: "utf8",
    timeout: 120_000,
    maxBuffer: 4 * 1024 * 1024,
    env: { ...process.env },
  });
  world.lastExitCode = r.status;
  world.lastStdout = r.stdout ?? "";
  world.lastStderr = r.stderr ?? "";
  world.notes.push(
    \`exerciseSurface: ran \${command} → exit \${r.status} (\${DISCOVERY_PRIMARY.confidence}: \${DISCOVERY_PRIMARY.reason})\`,
  );
  // Heuristic status clarity: non-empty output or known gate names
  const out = \`\${world.lastStdout}\\n\${world.lastStderr}\`;
  world.statusClear = out.trim().length > 0 || r.status === 0;
  world.nextActionObvious =
    /error|fail|fix|run |see |hint|path:/i.test(out) || r.status === 0;
  world.errorActionable =
    r.status !== 0 && /error|fail|ENOENT|must|required|path/i.test(out);
}

export function observeFailure(world: OptimizexpWorld): void {
  // Re-use exercise; failure scenarios may intentionally accept non-zero.
  exerciseSurface(world);
  if (world.lastExitCode === 0) {
    world.notes.push(
      "observeFailure: command succeeded; treat as soft fail for UX path or refine step",
    );
  }
  world.errorActionable =
    world.errorActionable ||
    (world.lastExitCode !== 0 &&
      \`\${world.lastStdout}\\n\${world.lastStderr}\`.trim().length > 0);
}

export function assertClearStatus(world: OptimizexpWorld): void {
  if (!world.statusClear) {
    throw new Error(
      \`Expected clear status from surface; notes=\${world.notes.join(" | ")} stdout=\${world.lastStdout.slice(0, 200)}\`,
    );
  }
}

export function assertNextActionObvious(world: OptimizexpWorld): void {
  if (!world.nextActionObvious && world.lastExitCode !== 0) {
    throw new Error(
      \`Expected obvious next action on failure; stderr=\${world.lastStderr.slice(0, 300)}\`,
    );
  }
}

export function assertErrorActionable(world: OptimizexpWorld): void {
  if (world.lastExitCode === 0) return; // success path ok
  if (!world.errorActionable) {
    throw new Error(
      \`Expected actionable error output; exit=\${world.lastExitCode}\`,
    );
  }
}

export function markEvidenceCapturable(world: OptimizexpWorld): void {
  world.evidencePath = \`.optimizexp/features/\${world.featureId}/evidence/\`;
  world.notes.push(\`evidence capturable under \${world.evidencePath}\`);
}
`;
}

export function generateBindingsStepsTs(featureId: string): string {
	return `/**
 * Cucumber step bindings for OptimizeXP feature \`${featureId}\`.
 * Thin adapters → implementations.ts (keeps Gherkin text stable).
 */
import { Given, Then, When } from "@cucumber/cucumber";
import {
  assertClearStatus,
  assertErrorActionable,
  assertNextActionObvious,
  exerciseSurface,
  markEvidenceCapturable,
  observeFailure,
  onCriticalPath,
  setFeatureContext,
  setPersona,
} from "./implementations.ts";
import { createWorld, type OptimizexpWorld } from "./world.ts";

// Cucumber World — attach helpers on \`this\`
function w(world: OptimizexpWorld | undefined): OptimizexpWorld {
  // cucumber may use World class; fall back to module singleton for simple runs
  return world ?? getSingleton();
}

let singleton: OptimizexpWorld | null = null;
function getSingleton(): OptimizexpWorld {
  singleton ??= createWorld(${JSON.stringify(featureId)});
  return singleton;
}

Given("persona {string} is active", function (this: OptimizexpWorld, personaId: string) {
  const world = this?.featureId ? this : getSingleton();
  if (!world.featureId) Object.assign(world, createWorld(${JSON.stringify(featureId)}));
  setPersona(world, personaId);
});

Given(
  "feature {string} is under optimizexp review",
  function (this: OptimizexpWorld, featureId: string) {
    const world = this?.featureId ? this : getSingleton();
    setFeatureContext(world, featureId);
  },
);

Given(
  "I am on the critical path described by the feature seed",
  function (this: OptimizexpWorld) {
    onCriticalPath(w(this));
  },
);

Given("something goes wrong on this journey", function (this: OptimizexpWorld) {
  const world = w(this);
  world.notes.push("failure path primed");
});

When("I exercise the surface as this persona would", function (this: OptimizexpWorld) {
  exerciseSurface(w(this));
});

When("I observe the failure as this persona", function (this: OptimizexpWorld) {
  observeFailure(w(this));
});

Then("I receive clear status about what happened", function (this: OptimizexpWorld) {
  assertClearStatus(w(this));
});

Then(
  "the next action is obvious without tribal knowledge",
  function (this: OptimizexpWorld) {
    assertNextActionObvious(w(this));
  },
);

Then("evidence is capturable for this scenario", function (this: OptimizexpWorld) {
  markEvidenceCapturable(w(this));
});

Then("the error is non-blaming and actionable", function (this: OptimizexpWorld) {
  assertErrorActionable(w(this));
});

Then(
  "I am not forced into repeated artificial hurdles",
  function (this: OptimizexpWorld) {
    // Structural: a single command attempt is enough for scaffold; agent refines.
    const world = w(this);
    if (world.notes.filter((n) => n.includes("exerciseSurface")).length > 3) {
      throw new Error("too many exercise attempts — friction signal");
    }
  },
);

// re-export for tests
export { createWorld, getSingleton };
`;
}

export function generateVitestStub(input: {
	featureId: string;
	hasPrimary: boolean;
}): string {
	return `/**
 * Vitest binding/smoke tests for OptimizeXP feature \`${input.featureId}\`.
 * Does not require Cucumber CLI; imports implementations directly.
 */
import { describe, expect, it } from "vitest";
import {
  DISCOVERY_PRIMARY,
  IMPLEMENTATION_STATUS,
  exerciseSurface,
  onCriticalPath,
  setFeatureContext,
  setPersona,
} from "../steps/implementations.ts";
import { createWorld } from "../steps/world.ts";

describe("optimizexp feature ${input.featureId} bindings", () => {
  it("exposes discovery metadata", () => {
    expect(IMPLEMENTATION_STATUS).toBeTruthy();
    expect(["wired", "stub"]).toContain(IMPLEMENTATION_STATUS.exerciseSurface);
  });

  it("sets persona and feature context", () => {
    const world = createWorld(${JSON.stringify(input.featureId)});
    setPersona(world, "developer");
    setFeatureContext(world, ${JSON.stringify(input.featureId)});
    expect(world.personaId).toBe("developer");
    expect(world.featureId).toBe(${JSON.stringify(input.featureId)});
  });

  it("critical path finds feature metadata", () => {
    const world = createWorld(${JSON.stringify(input.featureId)});
    setFeatureContext(world, ${JSON.stringify(input.featureId)});
    onCriticalPath(world);
    expect(world.notes.some((n) => n.includes("critical path"))).toBe(true);
  });

  it(${input.hasPrimary ? '"exerciseSurface runs discovered command (may non-zero)"' : '"exerciseSurface is stub without discovered command"'}, () => {
    const world = createWorld(${JSON.stringify(input.featureId)});
    setFeatureContext(world, ${JSON.stringify(input.featureId)});
    exerciseSurface(world);
    if (DISCOVERY_PRIMARY.command) {
      expect(world.lastCommand).toBe(DISCOVERY_PRIMARY.command);
      expect(world.lastExitCode === null || typeof world.lastExitCode === "number").toBe(
        true,
      );
    } else {
      expect(IMPLEMENTATION_STATUS.exerciseSurface).toBe("stub");
      expect(world.notes.some((n) => n.includes("STUB"))).toBe(true);
    }
  });
});
`;
}

export function generateBindingsReadme(
	featureId: string,
	primary: DiscoveredBinding | null,
): string {
	return `# Steps & tests — \`${featureId}\`

| Path | Role |
|---|---|
| \`world.ts\` | Shared Cucumber/world state |
| \`bindings.steps.ts\` | Given/When/Then → implementations |
| \`implementations.ts\` | Real or stub logic (discovery-wired when possible) |
| \`discovery.json\` | Code discovery report |
| \`../test/${featureId}.bindings.test.ts\` | Vitest smoke for bindings |

## Primary binding

${
	primary
		? `- **${primary.kind}** \`${primary.command ?? primary.path}\` (${primary.confidence})\n- ${primary.reason}`
		: "- None — implementations are stubs until a command/path is discovered or filled by the agent."
}

## Run

\`\`\`bash
# unit/smoke (vitest)
pnpm run test:file .optimizexp/features/${featureId}/test/${featureId}.bindings.test.ts

# cucumber (optimizexp profile, if configured)
pnpm run test:behavior:optimizexp -- --name "${featureId}"
# or:
node --import tsx node_modules/@cucumber/cucumber/bin/cucumber.js \\
  --config .optimizexp/cucumber.yaml \\
  --name "${featureId}"
\`\`\`

## Agent rules

1. Prefer wiring steps to **existing** package scripts / CLIs found in \`discovery.json\`.
2. If code does not exist, leave \`IMPLEMENTATION_STATUS\` as \`stub\` and record a finding (friction/uncertainty).
3. Do not call live external services from default steps.
4. Re-run discovery: \`generate-feature.mts --mode implement --id ${featureId}\`.
`;
}

export function buildImplementationsFromDiscovery(input: {
	featureId: string;
	report: DiscoveryReport;
}) {
	const primary = pickPrimaryCommand(input.report);
	return {
		primary,
		world: generateWorldTs(input.featureId),
		implementations: generateImplementationsTs({
			featureId: input.featureId,
			primary,
			report: input.report,
		}),
		bindings: generateBindingsStepsTs(input.featureId),
		vitest: generateVitestStub({
			featureId: input.featureId,
			hasPrimary: Boolean(primary),
		}),
		stepsReadme: generateBindingsReadme(input.featureId, primary),
	};
}
