"""Deterministic ``gauntlet next`` computation.

The response is advisory for navigation but is calculated from authoritative
durable state (ledger records, spec files, policies) and the command index —
never generated by an LLM.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from gauntlet.constants import CampaignState
from gauntlet.ledger import LedgerStore
from gauntlet.models import CampaignV1, CounterexampleV1
from gauntlet.paths import ProjectPaths, find_git_root


def _reference_for(state: str) -> str:
    mapping = {
        "project_init_required": "references/command-project.md",
        "spec_required": "references/command-spec.md",
        "spec_freeze_required": "references/command-spec.md",
        "campaign_required": "references/command-campaign.md",
        "observation_required": "references/command-observe.md",
        "diagnosis_required": "references/command-diagnose.md",
        "experiment_required": "references/command-experiment.md",
        "evaluation_required": "references/command-evaluate.md",
        "promotion_available": "references/command-promote.md",
        "campaign_stopped": "references/command-campaign.md",
    }
    return mapping.get(state, "references/architecture.md")


def compute_next(start: Path | None = None) -> dict[str, Any]:
    """Compute the next legal transitions from durable project state."""
    git_root = find_git_root(start)
    if git_root is None or not (git_root / ".gauntlet").is_dir():
        return _response(
            campaign_id=None,
            state="project_init_required",
            allowed=["gauntlet project init"],
            blocked=[],
            unresolved=[],
            approval_required=False,
        )
    paths = ProjectPaths(git_root=git_root)

    spec_file = paths.spec_dir / "gauntlet.yaml"
    spec_doc: dict[str, Any] | None = None
    if spec_file.is_file():
        loaded = yaml.safe_load(spec_file.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):
            spec_doc = loaded
    if spec_doc is None:
        return _response(
            campaign_id=None,
            state="spec_required",
            allowed=["gauntlet spec init"],
            blocked=[],
            unresolved=[],
            approval_required=False,
        )
    if not spec_doc.get("frozen", False):
        return _response(
            campaign_id=None,
            state="spec_freeze_required",
            allowed=["gauntlet spec validate", "gauntlet spec freeze"],
            blocked=[
                {
                    "command": "gauntlet campaign start",
                    "reason": "no frozen spec",
                }
            ],
            unresolved=[],
            approval_required=False,
        )

    ledger = LedgerStore(paths.ledger_dir)
    campaigns = ledger.load_all("campaigns", CampaignV1)
    active = [c for c in campaigns if c.state == CampaignState.ACTIVE]
    if not active:
        stopped = [c for c in campaigns if c.state == CampaignState.STOPPED]
        state = "campaign_stopped" if stopped and not active else "campaign_required"
        return _response(
            campaign_id=stopped[-1].campaign_id if state == "campaign_stopped" else None,
            state=state,
            allowed=["gauntlet campaign start"],
            blocked=[],
            unresolved=[],
            approval_required=False,
        )

    campaign = active[-1]
    unresolved = _unresolved_counterexamples(paths)
    experiments_dir = paths.ledger_dir / "experiments"
    has_experiments = experiments_dir.is_dir() and any(experiments_dir.glob("*.json"))
    promotions_dir = paths.ledger_dir / "promotions"
    has_promotion_evidence = promotions_dir.is_dir() and any(promotions_dir.glob("*.json"))

    if unresolved and not has_experiments:
        return _response(
            campaign_id=campaign.campaign_id,
            state="diagnosis_required",
            allowed=["gauntlet diagnosis record", "gauntlet campaign stop"],
            blocked=[
                {"command": "gauntlet promote apply", "reason": "no held-out result"}
            ],
            unresolved=unresolved,
            approval_required=False,
        )
    if not has_experiments:
        return _response(
            campaign_id=campaign.campaign_id,
            state="observation_required",
            allowed=[
                "gauntlet observe record",
                "gauntlet observe import",
                "gauntlet experiment propose",
                "gauntlet campaign stop",
            ],
            blocked=[
                {"command": "gauntlet promote apply", "reason": "no held-out result"}
            ],
            unresolved=unresolved,
            approval_required=False,
        )
    if not has_promotion_evidence:
        return _response(
            campaign_id=campaign.campaign_id,
            state="evaluation_required",
            allowed=[
                "gauntlet evaluate search",
                "gauntlet evaluate promotion",
                "gauntlet experiment compare",
                "gauntlet campaign stop",
            ],
            blocked=[
                {"command": "gauntlet promote apply", "reason": "no held-out result"}
            ],
            unresolved=unresolved,
            approval_required=False,
        )
    return _response(
        campaign_id=campaign.campaign_id,
        state="promotion_available",
        allowed=["gauntlet promote plan", "gauntlet promote apply", "gauntlet campaign stop"],
        blocked=[],
        unresolved=unresolved,
        approval_required=False,
    )


def _unresolved_counterexamples(paths: ProjectPaths) -> list[str]:
    records_dir = paths.counterexamples_dir / "records"
    unresolved: list[str] = []
    if not records_dir.is_dir():
        return unresolved
    import contextlib
    import json

    for record_file in sorted(records_dir.glob("*.json")):
        # Unreadable records are skipped here; `gauntlet audit integrity`
        # is the place that reports them.
        with contextlib.suppress(Exception):
            record = CounterexampleV1.model_validate(
                json.loads(record_file.read_text(encoding="utf-8"))
            )
            if record.status == "open":
                unresolved.append(record.counterexample_id)
    return unresolved


def _response(
    *,
    campaign_id: str | None,
    state: str,
    allowed: list[str],
    blocked: list[dict[str, str]],
    unresolved: list[str],
    approval_required: bool,
    stop: str | None = None,
) -> dict[str, Any]:
    return {
        "campaign_id": campaign_id,
        "state": state,
        "allowed_commands": allowed,
        "blocked_commands": blocked,
        "reference": _reference_for(state),
        "stop": stop,
        "unresolved": unresolved,
        "approval_required": approval_required,
    }
