"""Durable workflow service: generation, drift detection, run, self-healing.

``.gauntlet/workflows/`` holds one generated Microsoft Agent Framework
declarative YAML file per ``WorkflowPlanV1`` plus a ``<name>.plan.json``
sidecar (the canonical plan). The YAML is a *derived* artifact:

- generation is deterministic (same plan -> byte-identical YAML; stable key
  order, no timestamps in the YAML body);
- the YAML header binds it to its plan via ``# plan-digest: sha256:...``
  computed over the plan's canonical JSON;
- the YAML is literal-only: no PowerFx ``=`` expressions anywhere (they
  require a dotnet runtime, and the Python control plane is the single
  source of data flow); generation refuses any literal starting with ``=``;
- hand edits are detected as drift (``validate`` fails, ``sync`` reports a
  conflict) and are never silently overwritten.

Self-healing is a proposal seam, not an autonomous rewrite: ``heal`` turns a
recorded failure into a structured plan patch written as a proposal artifact
under ``.gauntlet/workflows/proposals/``. The gauntlet experiment/promotion
loop decides; only a promoted plan regenerates YAML. ``generate`` enforces
that lineage: a plan whose ``parent_plan_digest`` does not match the
currently deployed plan is refused unless the promote path passes
``force_promoted=True``.

Locking: the CLI layer holds the single project mutation lock around
mutating commands; this service does not acquire it itself.
"""

from __future__ import annotations

import json
import time
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from gauntlet.adapters.maf_workflow import (
    IntentVerifier,
    RunReport,
    Sleeper,
    StepExecutor,
    WorkflowRunner,
)
from gauntlet.canonical_json import digest_bytes, digest_value
from gauntlet.constants import ActionClass
from gauntlet.errors import (
    ConflictError,
    GateFailedError,
    InconclusiveError,
    InvalidInvocationError,
)
from gauntlet.models import WorkflowPlanV1, WorkflowStepV1
from gauntlet.paths import ProjectPaths, atomic_write_text
from gauntlet.redaction import Redactor
from gauntlet.support import Clock, SystemClock

GENERATED_HEADER = "# GENERATED by gauntlet workflow generate — do not edit by hand."

_APPROVAL_GATE_CLASSES = (ActionClass.R2, ActionClass.R3, ActionClass.R4)

_HEALABLE_OUTCOMES = ("dependency-unavailable", "approval-required", "gate-failed")


def plan_digest(plan: WorkflowPlanV1) -> str:
    """Digest over the plan's canonical JSON; the identity the YAML binds to."""
    return digest_value(plan.model_dump(mode="json"))


def _needs_approval_gate(step: WorkflowStepV1) -> bool:
    return step.require_approval or step.action_class in _APPROVAL_GATE_CLASSES


def _reject_powerfx(node: Any, where: str) -> None:
    if isinstance(node, str):
        if node.startswith("="):
            raise InvalidInvocationError(
                f"literal at {where} starts with '=' and would be parsed as a "
                "PowerFx expression; generated workflows are literal-only"
            )
        return
    if isinstance(node, Mapping):
        for key, value in node.items():
            _reject_powerfx(value, f"{where}.{key}")
        return
    if isinstance(node, list):
        for index, value in enumerate(node):
            _reject_powerfx(value, f"{where}[{index}]")


def render_workflow_yaml(plan: WorkflowPlanV1) -> str:
    """Deterministically render the declarative YAML for one plan.

    Every step becomes an ``InvokeFunctionTool`` action calling the
    ``gauntlet_step`` tool with literal arguments. Steps that require
    approval — explicitly or because they are R2+ — additionally get a
    ``RequestExternalInput`` action *before* them, so a human/host must
    supply approval input at runtime. This is defense in depth only: the
    ``gauntlet_step`` tool independently verifies a committed write-ahead
    intent for R2+ steps, and the gauntlet CLI enforces authority
    server-side, so editing the YAML cannot bypass authority.
    """
    actions: list[dict[str, Any]] = []
    for step in plan.steps:
        if _needs_approval_gate(step):
            actions.append(
                {
                    "kind": "RequestExternalInput",
                    "id": f"approve_{step.step_id}",
                    "displayName": f"Approval gate: {step.display_name}",
                    "prompt": (
                        f"Approve step '{step.step_id}' ({step.action_class.value})? "
                        "Respond 'approved' to continue."
                    ),
                    "variable": f"Local.approval_{step.step_id}",
                }
            )
        actions.append(
            {
                "kind": "InvokeFunctionTool",
                "id": step.step_id,
                "displayName": step.display_name,
                "functionName": "gauntlet_step",
                "arguments": {
                    "step_id": step.step_id,
                    "command": list(step.command),
                    "action_class": step.action_class.value,
                    "require_approval": step.require_approval,
                    "max_retries": step.max_retries,
                    "retry_on_exit_codes": list(step.retry_on_exit_codes),
                    "on_gate_failure": step.on_gate_failure,
                    "timeout_seconds": step.timeout_seconds,
                },
            }
        )
    document = {
        "name": plan.workflow_name,
        "description": plan.description,
        "actions": actions,
    }
    _reject_powerfx(document, plan.workflow_name)
    body = yaml.safe_dump(
        document, sort_keys=False, default_flow_style=False, allow_unicode=True, width=100
    )
    return f"{GENERATED_HEADER}\n# plan-digest: {plan_digest(plan)}\n{body}"


def _render_plan_json(plan: WorkflowPlanV1) -> str:
    return json.dumps(plan.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"


def _first_difference(expected: str, actual: str) -> str:
    expected_lines = expected.splitlines()
    actual_lines = actual.splitlines()
    for number, (want, got) in enumerate(zip(expected_lines, actual_lines, strict=False), 1):
        if want != got:
            return f"first difference at line {number}: expected {want!r}, found {got!r}"
    return (
        f"line counts differ: expected {len(expected_lines)} lines, "
        f"found {len(actual_lines)}"
    )


@dataclass(frozen=True)
class GeneratedWorkflow:
    workflow_name: str
    yaml_path: str
    plan_path: str
    plan_digest: str
    yaml_digest: str


@dataclass(frozen=True)
class WorkflowStatusEntry:
    workflow_name: str
    plan_digest: str
    drifted: bool
    last_run_status: str | None
    last_run_at: str | None
    attempt_count: int


@dataclass(frozen=True)
class RepairProposal:
    """Structured self-healing candidate; the promotion loop decides."""

    proposal_id: str
    workflow_name: str
    path: str
    patch: dict[str, Any]
    failure: dict[str, Any]
    parent_plan_digest: str
    candidate_plan: WorkflowPlanV1


class WorkflowService:
    """CLI-facing service over ``.gauntlet/workflows/`` and the MAF runner."""

    def __init__(
        self,
        paths: ProjectPaths,
        *,
        executor: StepExecutor | None = None,
        clock: Clock | None = None,
        sleeper: Sleeper | None = None,
        intent_verifier: IntentVerifier | None = None,
        redactor: Redactor | None = None,
    ) -> None:
        self._paths = paths
        self._executor = executor
        self._clock = clock if clock is not None else SystemClock()
        self._sleeper = sleeper if sleeper is not None else time.sleep
        self._intent_verifier = intent_verifier
        self._redactor = redactor if redactor is not None else Redactor()

    # -- paths ------------------------------------------------------------

    def yaml_path(self, name: str) -> Path:
        return self._paths.workflows_dir / f"{name}.yaml"

    def plan_path(self, name: str) -> Path:
        return self._paths.workflows_dir / f"{name}.plan.json"

    def load_plan(self, name: str) -> WorkflowPlanV1:
        path = self.plan_path(name)
        if not path.is_file():
            raise InvalidInvocationError(
                f"no workflow plan named {name!r} in .gauntlet/workflows/",
                hint="generate it with `gauntlet workflow generate`",
            )
        return WorkflowPlanV1.model_validate(json.loads(path.read_text(encoding="utf-8")))

    # -- generation and drift ---------------------------------------------

    def generate(
        self, plan: WorkflowPlanV1, *, force_promoted: bool = False
    ) -> GeneratedWorkflow:
        """Write the YAML and plan sidecar atomically, enforcing lineage.

        A plan that differs from the currently deployed one is accepted only
        when its ``parent_plan_digest`` equals the deployed plan's digest
        (the normal promote flow for a healed plan) or when the promote path
        explicitly passes ``force_promoted=True``. Regenerating the identical
        plan is always allowed (idempotent).
        """
        new_digest = plan_digest(plan)
        plan_file = self.plan_path(plan.workflow_name)
        if plan_file.is_file():
            deployed = WorkflowPlanV1.model_validate(
                json.loads(plan_file.read_text(encoding="utf-8"))
            )
            deployed_digest = plan_digest(deployed)
            if (
                new_digest != deployed_digest
                and not force_promoted
                and plan.parent_plan_digest != deployed_digest
            ):
                raise ConflictError(
                    f"plan for workflow {plan.workflow_name!r} does not descend from "
                    f"the deployed plan ({deployed_digest})",
                    hint=(
                        "promote the plan through the gauntlet loop (its "
                        "parent_plan_digest must equal the deployed plan digest), "
                        "or pass force_promoted=True from the promote path"
                    ),
                )
        rendered = render_workflow_yaml(plan)
        atomic_write_text(self.plan_path(plan.workflow_name), _render_plan_json(plan))
        atomic_write_text(self.yaml_path(plan.workflow_name), rendered)
        return GeneratedWorkflow(
            workflow_name=plan.workflow_name,
            yaml_path=str(self.yaml_path(plan.workflow_name)),
            plan_path=str(self.plan_path(plan.workflow_name)),
            plan_digest=new_digest,
            yaml_digest=digest_bytes(rendered.encode("utf-8")),
        )

    def validate(self, name: str) -> str:
        """Verify digest binding, byte-exact rendering, and loader acceptance.

        Returns the plan digest on success; raises ``GateFailedError`` with a
        diff hint on drift (hand-edited YAML, or YAML from a different plan).
        """
        plan = self.load_plan(name)
        expected = render_workflow_yaml(plan)
        yaml_file = self.yaml_path(name)
        if not yaml_file.is_file():
            raise GateFailedError(
                f"workflow YAML for {name!r} is missing",
                hint="run `gauntlet workflow sync` to regenerate it from the plan",
            )
        actual = yaml_file.read_text(encoding="utf-8")
        if actual != expected:
            raise GateFailedError(
                f"workflow YAML for {name!r} has drifted from its plan",
                hint=(
                    _first_difference(expected, actual)
                    + "; regenerate from the plan or promote a repaired plan "
                    "instead of editing YAML by hand"
                ),
            )
        self._loader_check(actual)
        return plan_digest(plan)

    def _loader_check(self, yaml_text: str) -> None:
        """Prove the installed MAF loader accepts the generated YAML."""
        # Importing gauntlet.adapters.maf_workflow above already imported the
        # declarative package with its ExperimentalWarning suppressed.
        from agent_framework.declarative import WorkflowFactory

        def _noop_step(**_kwargs: Any) -> dict[str, Any]:
            return {}

        factory = WorkflowFactory()
        factory.register_tool("gauntlet_step", _noop_step)
        factory.create_workflow_from_yaml(yaml_text)

    def sync(self) -> dict[str, list[str]]:
        """Regenerate every YAML from its plan; report drift, never overwrite.

        Missing YAML is regenerated. YAML that differs from its plan's
        rendering is reported via ``ConflictError`` and left untouched.
        """
        workflows_dir = self._paths.workflows_dir
        regenerated: list[str] = []
        unchanged: list[str] = []
        drifted: list[str] = []
        if workflows_dir.is_dir():
            for plan_file in sorted(workflows_dir.glob("*.plan.json")):
                name = plan_file.name[: -len(".plan.json")]
                plan = self.load_plan(name)
                expected = render_workflow_yaml(plan)
                yaml_file = self.yaml_path(name)
                if not yaml_file.is_file():
                    atomic_write_text(yaml_file, expected)
                    regenerated.append(name)
                elif yaml_file.read_text(encoding="utf-8") == expected:
                    unchanged.append(name)
                else:
                    drifted.append(name)
        if drifted:
            raise ConflictError(
                "hand-edited workflow YAML detected; not overwritten: "
                + ", ".join(f"{name}.yaml" for name in drifted),
                hint=(
                    "workflow YAML is generated; edit the plan and promote it, "
                    "or delete the drifted YAML and run sync again"
                ),
            )
        return {"regenerated": regenerated, "unchanged": unchanged}

    def status(self) -> list[WorkflowStatusEntry]:
        """List every deployed plan with drift state and last-run summary."""
        entries: list[WorkflowStatusEntry] = []
        workflows_dir = self._paths.workflows_dir
        if not workflows_dir.is_dir():
            return entries
        for plan_file in sorted(workflows_dir.glob("*.plan.json")):
            name = plan_file.name[: -len(".plan.json")]
            plan = self.load_plan(name)
            digest = plan_digest(plan)
            yaml_file = self.yaml_path(name)
            drifted = (
                not yaml_file.is_file()
                or yaml_file.read_text(encoding="utf-8") != render_workflow_yaml(plan)
            )
            last_status: str | None = None
            last_at: str | None = None
            attempt_count = 0
            journal_file = self._paths.workflow_checkpoints_dir / name / "journal.json"
            if journal_file.is_file():
                journal = json.loads(journal_file.read_text(encoding="utf-8"))
                last_status = journal.get("status")
                last_at = journal.get("updated_at")
                attempt_count = len(journal.get("attempts", []))
            entries.append(
                WorkflowStatusEntry(
                    workflow_name=name,
                    plan_digest=digest,
                    drifted=drifted,
                    last_run_status=last_status,
                    last_run_at=last_at,
                    attempt_count=attempt_count,
                )
            )
        return entries

    # -- execution ---------------------------------------------------------

    def _runner(self) -> WorkflowRunner:
        if self._executor is None:
            raise InvalidInvocationError(
                "no step executor is wired into the workflow service",
                hint="the CLI injects the real gauntlet subprocess executor",
            )
        return WorkflowRunner(
            checkpoints_root=self._paths.workflow_checkpoints_dir,
            executor=self._executor,
            clock=self._clock,
            sleeper=self._sleeper,
            redactor=self._redactor,
            intent_verifier=self._intent_verifier,
        )

    def run(
        self,
        name: str,
        *,
        inputs: Mapping[str, str] | None = None,
        non_interactive: bool = False,
    ) -> RunReport:
        """Validate the binding, then execute the workflow via the runner.

        The runner never prompts: approvals always pause the run cleanly and
        are answered through ``resume``, so ``non_interactive`` only records
        the caller's intent (both modes behave identically here).
        """
        del non_interactive
        digest = self.validate(name)
        plan = self.load_plan(name)
        yaml_text = self.yaml_path(name).read_text(encoding="utf-8")
        return self._runner().run(plan, yaml_text, digest, inputs=inputs)

    def resume(self, name: str) -> RunReport:
        """Continue a paused run from its checkpoint (or journal replay)."""
        digest = self.validate(name)
        plan = self.load_plan(name)
        yaml_text = self.yaml_path(name).read_text(encoding="utf-8")
        return self._runner().resume(plan, yaml_text, digest)

    # -- self-healing --------------------------------------------------------

    def heal(
        self, name: str, failure: Mapping[str, Any] | None = None
    ) -> RepairProposal:
        """Turn a recorded failure into a structured plan-patch proposal.

        Deterministic repairs:

        - exit 8 (dependency unavailable): raise ``max_retries`` on the
          failing step;
        - exit 3 (approval required): set ``require_approval`` so the
          regenerated YAML gains an explicit approval gate before the step;
        - exit 4 (gate failed): set ``require_approval`` so a human reviews
          the gate evidence before the step re-runs.

        Anything else raises ``InconclusiveError``: there is no deterministic
        repair, so a diagnosis must be recorded instead. The proposal is an
        artifact only — the experiment/promotion loop decides, and only a
        promoted plan (``parent_plan_digest`` matching the deployed digest)
        regenerates YAML through ``generate``.
        """
        plan = self.load_plan(name)
        deployed_digest = plan_digest(plan)
        failure_record = dict(failure) if failure is not None else self._last_failure(name)
        step_id = str(failure_record.get("step_id", ""))
        exit_code = failure_record.get("exit_code")
        step = next((s for s in plan.steps if s.step_id == step_id), None)
        if step is None:
            raise InvalidInvocationError(
                f"failure references unknown step {step_id!r} in workflow {name!r}"
            )
        patch = self._propose_patch(step, exit_code)
        proposals_dir = self._paths.workflows_dir / "proposals"
        existing = sorted(proposals_dir.glob(f"{name}-repair-*.json"))
        sequence = len(existing) + 1
        proposal_id = f"repair:{name}/{sequence:03d}"
        candidate = self._patched_plan(plan, deployed_digest, proposal_id, patch)
        proposal_path = proposals_dir / f"{name}-repair-{sequence:03d}.json"
        document = {
            "schema_version": "dev.gauntlet.workflow-repair-proposal/v1",
            "proposal_id": proposal_id,
            "workflow_name": name,
            "failure": failure_record,
            "patch": patch,
            "parent_plan_digest": deployed_digest,
            "candidate_plan": candidate.model_dump(mode="json"),
            "created_at": self._clock.now(),
        }
        atomic_write_text(proposal_path, json.dumps(document, indent=2, sort_keys=True) + "\n")
        return RepairProposal(
            proposal_id=proposal_id,
            workflow_name=name,
            path=str(proposal_path),
            patch=patch,
            failure=failure_record,
            parent_plan_digest=deployed_digest,
            candidate_plan=candidate,
        )

    def _last_failure(self, name: str) -> dict[str, Any]:
        journal_file = self._paths.workflow_checkpoints_dir / name / "journal.json"
        if not journal_file.is_file():
            raise InvalidInvocationError(
                f"no run journal for workflow {name!r}; nothing to heal",
                hint="pass an explicit failure, or run the workflow first",
            )
        journal = json.loads(journal_file.read_text(encoding="utf-8"))
        for attempt in reversed(journal.get("attempts", [])):
            if attempt.get("outcome") in _HEALABLE_OUTCOMES:
                return {
                    "step_id": attempt.get("step_id"),
                    "exit_code": attempt.get("exit_code"),
                    "outcome": attempt.get("outcome"),
                }
        raise InvalidInvocationError(
            f"the last run of workflow {name!r} has no healable failure",
            hint="only dependency, approval, and gate failures have deterministic repairs",
        )

    def _propose_patch(self, step: WorkflowStepV1, exit_code: Any) -> dict[str, Any]:
        if exit_code == 8:
            return {
                "kind": "raise-max-retries",
                "step_id": step.step_id,
                "from_value": step.max_retries,
                "to_value": min(step.max_retries + 2, 10),
            }
        if exit_code in (3, 4):
            return {
                "kind": "require-approval",
                "step_id": step.step_id,
                "from_value": step.require_approval,
                "to_value": True,
            }
        raise InconclusiveError(
            f"no deterministic repair for exit code {exit_code!r} on step "
            f"{step.step_id!r}",
            hint="record a diagnosis and propose an experiment instead",
        )

    def _patched_plan(
        self,
        plan: WorkflowPlanV1,
        deployed_digest: str,
        proposal_id: str,
        patch: Mapping[str, Any],
    ) -> WorkflowPlanV1:
        steps: list[WorkflowStepV1] = []
        for step in plan.steps:
            if step.step_id != patch["step_id"]:
                steps.append(step)
            elif patch["kind"] == "raise-max-retries":
                steps.append(step.model_copy(update={"max_retries": patch["to_value"]}))
            else:
                steps.append(step.model_copy(update={"require_approval": True}))
        repair_suffix = proposal_id.rsplit("/", 1)[1]
        return plan.model_copy(
            update={
                "plan_id": f"{plan.plan_id}/repair-{repair_suffix}",
                "steps": steps,
                "parent_plan_digest": deployed_digest,
                "repairs_applied": [*plan.repairs_applied, proposal_id],
                "created_at": self._clock.now(),
            }
        )
